---
# Based on this guide:
# https://www.tecmint.com/install-virtualbox-guest-additions-on-centos-8/
- name: Enable EPEL-repo
  become: yes
  yum:
    name: epel-release
    state: latest
  when: ansible_distribution_file_variety == "RedHat"

- name: Install some basic tools (DNF)
  become: yes
  dnf:
    name:
     - gcc
     - make
     - perl
     - kernel-devel
     - kernel-headers
     - bzip2
     - dkms
    state: present
  when: ansible_distribution_file_variety == "RedHat"

- name: "Create /mnt/cdrom"
  become: yes
  file:
    path: "/mnt/cdrom"
    state: directory
    owner: "root"
    group: "root"

- include_role:
    name: commons
    tasks_from: menu
  vars:
    menu:
      caption: "Download and insert the VirtualBox Guest Additions ISO-image into your virtual machine as a CD/DVD"
      question: "Your choice"
      options:
        - name: Continue
          option: c
          value: c
          default: true
        - name: Abort
          option: a
          value: a

- fail:
    msg: "Aborted by user"
  when: menu_result == 'a'

- name: "Mount cdrom temporary"
  become: yes
  shell:
    cmd: "mount /dev/cdrom /mnt/cdrom"

- name: "Run VirtualBox Guest Additions setup"
  become: yes
  shell:
    cmd: "./VBoxLinuxAdditions.run --nox11"
    chdir: /mnt/cdrom

- include_role:
    name: commons
    tasks_from: menu
  vars:
    menu:
      caption: "Make sure a shared folder namned 'workspace' exists in virtual machine"
      question: "Your choice"
      options:
        - name: Continue
          option: c
          value: c
          default: true
        - name: Abort
          option: a
          value: a

- fail:
    msg: "Aborted by user"
  when: menu_result == 'a'

- name: "Create dir for workspace mount"
  become: yes
  file:
    path: "/home/{{ applications_devmode_user }}/workspace"
    state: directory
    owner: "{{ applications_devmode_user }}"
    group: "{{ applications_devmode_user }}"

- name: "Mount the dev repo with overlay in the application repos-folder (overlay)"
  become: yes
  mount:
    src: "workspace"
    path: "/home/{{ applications_devmode_user }}/workspace"
    fstype: vboxsf # VirtualBox Shared Folder
    opts: |-
      rw                                   {#- Read/write -#}
      ,uid={{ applications_devmode_user }} {#- owner for all files -#}
      ,gid={{ applications_devmode_user }} {#- group for all files -#}
    state: mounted
