---

- name: "Get Latest version number of Sass from GitHub"
  shell: >-
    curl -s https://api.github.com/repos/sass/dart-sass/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'
  args:
    # Warning om att inte shell ska användas för curl:
    warn: false
  register: sass_latest_version_output
  changed_when: false

- set_fact:
    sass_latest_version: "{{ sass_latest_version_output.stdout }}"

- name: "Create /opt/sass"
  become: yes
  file:
    path: "/opt/sass{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  loop:
    - ""
    - "/dart-sass-{{ sass_latest_version }}"

- name: "Download and unzip latest sass"
  become: yes
  become_user: "root"
  unarchive:
    remote_src: yes
    src: "https://github.com/sass/dart-sass/releases/download/{{ sass_latest_version }}/dart-sass-{{ sass_latest_version }}-linux-x64.tar.gz"
    dest: "/opt/sass/dart-sass-{{ sass_latest_version }}"
    mode: "u=rwX,g=rX,o=rX"
    owner: "root"
    group: "root"
    creates: "/opt/sass/dart-sass-{{ sass_latest_version }}/dart-sass"

- name: "Set file permissions for sass"
  become: yes
  file:
    path: "/opt/sass"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
    recurse: true


# Måste vara absolut path i symlink för att sass ska hitta sin dart!
- name: "Symlink sass"
  become: yes
  file:
    path: "/opt/sass/sass"
    src: "/opt/sass/dart-sass-{{ sass_latest_version }}/dart-sass/sass"
    owner: "root"
    group: "root"
    mode: "u=rwx,g=rx,o=rx"
    state: link
    force: yes

# Orginal på ubuntu: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
- name: "Add sass path to path (Debian)"
  become: yes
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: 'PATH=(["]?)((?!.*?{{ sass_path }}).*?)(["]?)$'
    line: 'PATH=\1\2:{{ sass_path }}\3'
  vars:
    sass_path: "/opt/sass"
  when: ansible_os_family == "Debian"


- name: "Add sass to global path (RedHat)"
  become: yes
  template:
    src: profile_sass.sh.j2
    dest: /etc/profile.d/sass.sh
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: ansible_distribution_file_variety == "RedHat"