---

- name: "Install NFS (YUM)"
  become: yes
  yum:
    name:
      - nfs-utils
    state: present
  when: ansible_distribution_file_variety == "RedHat"

- name: "Get uid for owner of exports"
  getent:
    database: passwd
#    key: "{{ item }}"
# Registrerar i getent_passwd
#  "getent_passwd": {
#        "adm": [
#            "x",
#            "3", #uid
#            "4", #gid
#            "adm",
#            "/var/adm",
#            "/sbin/nologin" #shell
#        ],
#        "apache": [
#            "x",
#            "48",
#            "48",
#            "Apache",
#            "/usr/share/httpd",
#            "/sbin/nologin"
#        ],
#        ...

- name: "Create /etc/exports for NFS"
  become: yes
  template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: "Reload NFS"

- name: "Ensure NFS is running"
  become: yes
  service:
    name: "nfs-server"
    state: started
    enabled: yes
  when: nfs.exports | length
